"""Typed response models for news articles attached to TurnResult.

These are backend-owned Pydantic schemas that mirror the composer output
shape.  They decouple the API contract from the news_agent dataclasses
so the backend can validate and document the response independently.
"""

from typing import List, Optional

from pydantic import BaseModel


class NewsHistoricalExample(BaseModel):
    """Beginner-friendly historical analog panel."""

    title: str
    why_similar: str
    what_happened: str
    beginner_takeaway: str
    source_event_ids: List[str]


class NewsArticle(BaseModel):
    """Narrative-only news article generated by the news_agent composer.

    This model is OUTPUT-ONLY — it never influences simulation logic.
    """

    headline: str
    short_bulletin: str
    beginner_explanation: str
    historical_example: Optional[NewsHistoricalExample] = None
    selected_event_ids: List[str]
    generation_mode: str
    validation_flags: List[str]
