"""
Regime Library — Wealth Manager Arena
======================================
All numbers here are STATIC configuration, NOT generated by an LLM.
Each regime defines bounded drift ranges and volatility multipliers per asset class.
The simulation engine samples within these bounds using seeded RNG.

Drift ranges are in percentage points per turn (monthly or yearly).
Shock ranges are worst-case single-turn drops when a shock event fires.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Tuple

from app.core.constants import AssetClass, Difficulty, RegimeType, VolatilityLevel


@dataclass
class AssetBehavior:
    """
    Bounded behavior specification for one asset class within one regime.

    drift_range:            (min%, max%) expected return per turn under this regime.
    volatility_multiplier:  scales the asset's base volatility. >1 = more nervous.
    shock_range:            (min%, max%) one-turn drop when a regime shock fires.
                            Both values should be negative (losses).
    """

    drift_range: Tuple[float, float]
    volatility_multiplier: float
    shock_range: Tuple[float, float]


# Base 1-sigma volatility per asset, per turn (%)
# Used by the turn engine to add bounded noise around the drift.
BASE_VOLATILITY: Dict[str, float] = {
    AssetClass.EQUITIES: 4.0,
    AssetClass.BONDS: 1.5,
    AssetClass.FX: 1.0,
    AssetClass.GOLD: 2.5,
    AssetClass.CRYPTO: 15.0,
}


@dataclass
class RegimeTemplate:
    type: RegimeType
    label: str
    description: str
    volatility_level: VolatilityLevel
    # how many turns this regime typically lasts (min, max)
    duration_turns_range: Tuple[int, int]
    # probability per turn that a market shock fires (on top of scheduled events)
    shock_probability_per_turn: float
    # per-asset behavior under this regime
    asset_behaviors: Dict[str, AssetBehavior]
    # event types that are typical / likely during this regime
    typical_event_types: List[str]
    # "high" = assets move together, "low" = independent, "mixed"
    correlation_tendency: str
    # description of the reference portfolio used for benchmarking
    benchmark_label: str


# ---------------------------------------------------------------------------
# Regime Library — 10 regimes covering the full macro spectrum
# ---------------------------------------------------------------------------

REGIME_LIBRARY: Dict[str, RegimeTemplate] = {

    RegimeType.BULL_GROWTH: RegimeTemplate(
        type=RegimeType.BULL_GROWTH,
        label="Bull Market – Growth Phase",
        description=(
            "Broad economic expansion. Equities rise steadily. Bonds flat to slightly "
            "negative as rates normalise. Crypto rallies strongly."
        ),
        volatility_level=VolatilityLevel.LOW,
        duration_turns_range=(12, 36),
        shock_probability_per_turn=0.05,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(0.5, 3.0),
                volatility_multiplier=0.8,
                shock_range=(-5.0, -2.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-0.3, 0.5),
                volatility_multiplier=0.6,
                shock_range=(-1.5, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-0.5, 0.5),
                volatility_multiplier=0.7,
                shock_range=(-1.0, -0.3),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(-0.5, 1.0),
                volatility_multiplier=0.7,
                shock_range=(-3.0, -1.0),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(1.0, 8.0),
                volatility_multiplier=1.0,
                shock_range=(-15.0, -5.0),
            ),
        },
        typical_event_types=["earnings_shock", "recovery_signal", "central_bank_decision"],
        correlation_tendency="low",
        benchmark_label="Balanced (60% equities / 40% bonds)",
    ),

    RegimeType.RECESSION: RegimeTemplate(
        type=RegimeType.RECESSION,
        label="Recession",
        description=(
            "Economic contraction. Equities fall broadly. Bonds rally as safe haven. "
            "Gold holds value. Crypto drops sharply."
        ),
        volatility_level=VolatilityLevel.HIGH,
        duration_turns_range=(6, 18),
        shock_probability_per_turn=0.20,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(-3.0, 0.5),
                volatility_multiplier=1.5,
                shock_range=(-10.0, -4.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(0.5, 2.5),
                volatility_multiplier=0.8,
                shock_range=(-2.0, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-1.0, 1.0),
                volatility_multiplier=1.0,
                shock_range=(-2.0, -0.5),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(0.5, 2.0),
                volatility_multiplier=0.9,
                shock_range=(-3.0, -1.0),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-5.0, 0.5),
                volatility_multiplier=1.8,
                shock_range=(-20.0, -8.0),
            ),
        },
        typical_event_types=[
            "recession_warning", "banking_stress", "earnings_shock", "central_bank_decision"
        ],
        correlation_tendency="high",
        benchmark_label="Defensive (20% equities / 60% bonds / 20% gold)",
    ),

    RegimeType.INFLATION_SHOCK: RegimeTemplate(
        type=RegimeType.INFLATION_SHOCK,
        label="Inflation Shock",
        description=(
            "Sudden inflation surge above expectations. Bonds are crushed in real terms. "
            "Gold shines as an inflation hedge. Equities struggle with margin pressure."
        ),
        volatility_level=VolatilityLevel.HIGH,
        duration_turns_range=(6, 24),
        shock_probability_per_turn=0.15,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(-1.5, 1.0),
                volatility_multiplier=1.2,
                shock_range=(-8.0, -3.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-2.5, -0.5),
                volatility_multiplier=1.1,
                shock_range=(-4.0, -1.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-1.0, 1.5),
                volatility_multiplier=1.0,
                shock_range=(-2.0, -0.5),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(1.0, 3.5),
                volatility_multiplier=1.0,
                shock_range=(-4.0, -1.5),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-2.0, 3.0),
                volatility_multiplier=1.5,
                shock_range=(-20.0, -7.0),
            ),
        },
        typical_event_types=[
            "inflation_surprise", "central_bank_decision", "commodity_supply_disruption"
        ],
        correlation_tendency="mixed",
        benchmark_label="Inflation-Hedged (30% equities / 20% bonds / 30% gold / 20% commodities)",
    ),

    RegimeType.RATE_HIKE_CYCLE: RegimeTemplate(
        type=RegimeType.RATE_HIKE_CYCLE,
        label="Rate Hike Cycle",
        description=(
            "Central banks raise rates aggressively to fight inflation. "
            "Bonds fall. Growth stocks and crypto face valuation pressure."
        ),
        volatility_level=VolatilityLevel.MEDIUM,
        duration_turns_range=(6, 18),
        shock_probability_per_turn=0.10,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(-1.0, 1.5),
                volatility_multiplier=1.0,
                shock_range=(-7.0, -2.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-2.0, -0.3),
                volatility_multiplier=1.0,
                shock_range=(-3.5, -1.0),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-0.5, 1.5),
                volatility_multiplier=1.1,
                shock_range=(-1.5, -0.3),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(-1.0, 0.5),
                volatility_multiplier=0.9,
                shock_range=(-3.0, -1.0),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-3.0, 1.0),
                volatility_multiplier=1.3,
                shock_range=(-18.0, -6.0),
            ),
        },
        typical_event_types=["central_bank_decision", "inflation_surprise"],
        correlation_tendency="mixed",
        benchmark_label="Conservative (30% equities / 50% bonds / 20% cash)",
    ),

    RegimeType.STAGFLATION: RegimeTemplate(
        type=RegimeType.STAGFLATION,
        label="Stagflation",
        description=(
            "High inflation combined with stagnant growth — worst of both worlds. "
            "Bonds suffer. Gold is one of the few safe havens."
        ),
        volatility_level=VolatilityLevel.HIGH,
        duration_turns_range=(6, 18),
        shock_probability_per_turn=0.15,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(-2.0, 0.5),
                volatility_multiplier=1.3,
                shock_range=(-9.0, -3.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-2.0, 0.0),
                volatility_multiplier=1.0,
                shock_range=(-4.0, -1.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-1.5, 1.0),
                volatility_multiplier=1.1,
                shock_range=(-2.5, -0.8),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(1.0, 3.0),
                volatility_multiplier=1.0,
                shock_range=(-3.5, -1.0),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-4.0, 1.0),
                volatility_multiplier=1.6,
                shock_range=(-22.0, -8.0),
            ),
        },
        typical_event_types=[
            "inflation_surprise", "recession_warning",
            "commodity_supply_disruption", "central_bank_decision",
        ],
        correlation_tendency="high",
        benchmark_label="Gold-Weighted (25% equities / 25% bonds / 30% gold / 20% commodities)",
    ),

    RegimeType.BANKING_PANIC: RegimeTemplate(
        type=RegimeType.BANKING_PANIC,
        label="Banking Panic",
        description=(
            "Systemic stress in the financial sector. Equities crash. Gold surges. "
            "Crypto implodes. Bonds rally as capital flees to safety."
        ),
        volatility_level=VolatilityLevel.EXTREME,
        duration_turns_range=(3, 12),
        shock_probability_per_turn=0.30,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(-5.0, 1.0),
                volatility_multiplier=2.0,
                shock_range=(-15.0, -5.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(0.0, 3.0),
                volatility_multiplier=0.9,
                shock_range=(-2.5, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-2.0, 2.0),
                volatility_multiplier=1.5,
                shock_range=(-3.0, -1.0),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(1.5, 4.0),
                volatility_multiplier=1.1,
                shock_range=(-4.0, -1.5),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-8.0, 2.0),
                volatility_multiplier=2.0,
                shock_range=(-30.0, -10.0),
            ),
        },
        typical_event_types=[
            "banking_stress", "central_bank_decision",
            "recession_warning", "geopolitical_escalation",
        ],
        correlation_tendency="high",
        benchmark_label="Cash-Heavy (10% equities / 40% bonds / 30% gold / 20% cash)",
    ),

    RegimeType.COMMODITY_BOOM: RegimeTemplate(
        type=RegimeType.COMMODITY_BOOM,
        label="Commodity Boom",
        description=(
            "Raw material prices surge broadly. Gold and commodities lead. "
            "Energy and materials equity sectors benefit. Bonds largely flat."
        ),
        volatility_level=VolatilityLevel.MEDIUM,
        duration_turns_range=(6, 24),
        shock_probability_per_turn=0.10,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(0.0, 2.0),
                volatility_multiplier=0.9,
                shock_range=(-6.0, -2.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-0.5, 0.5),
                volatility_multiplier=0.7,
                shock_range=(-2.0, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-0.5, 1.0),
                volatility_multiplier=0.8,
                shock_range=(-1.5, -0.3),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(1.0, 4.0),
                volatility_multiplier=1.1,
                shock_range=(-5.0, -1.5),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-1.0, 3.0),
                volatility_multiplier=1.2,
                shock_range=(-15.0, -5.0),
            ),
        },
        typical_event_types=[
            "commodity_supply_disruption", "inflation_surprise", "geopolitical_escalation"
        ],
        correlation_tendency="low",
        benchmark_label="Commodity-Tilted (35% equities / 20% bonds / 30% gold / 15% commodities)",
    ),

    RegimeType.GEOPOLITICAL_CRISIS: RegimeTemplate(
        type=RegimeType.GEOPOLITICAL_CRISIS,
        label="Geopolitical Crisis",
        description=(
            "War, major conflict, or systemic geopolitical disruption. "
            "Markets deeply uncertain. Gold spikes. Equities and crypto fall."
        ),
        volatility_level=VolatilityLevel.HIGH,
        duration_turns_range=(6, 24),
        shock_probability_per_turn=0.25,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(-3.0, 0.5),
                volatility_multiplier=1.6,
                shock_range=(-12.0, -4.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(0.0, 2.0),
                volatility_multiplier=0.8,
                shock_range=(-2.5, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-2.0, 2.0),
                volatility_multiplier=1.5,
                shock_range=(-3.0, -0.8),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(1.0, 4.5),
                volatility_multiplier=1.2,
                shock_range=(-4.5, -1.5),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(-3.0, 2.0),
                volatility_multiplier=1.7,
                shock_range=(-25.0, -8.0),
            ),
        },
        typical_event_types=[
            "geopolitical_escalation", "commodity_supply_disruption",
            "banking_stress", "central_bank_decision",
        ],
        correlation_tendency="high",
        benchmark_label="Defensive (20% equities / 35% bonds / 35% gold / 10% cash)",
    ),

    RegimeType.POST_CRASH_RECOVERY: RegimeTemplate(
        type=RegimeType.POST_CRASH_RECOVERY,
        label="Post-Crash Recovery",
        description=(
            "Markets rebound after a crash. Equities lead the recovery. "
            "Crypto can deliver outsized returns. Bonds steady. Volatility remains elevated."
        ),
        volatility_level=VolatilityLevel.MEDIUM,
        duration_turns_range=(12, 24),
        shock_probability_per_turn=0.08,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(1.0, 4.0),
                volatility_multiplier=1.1,
                shock_range=(-8.0, -3.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-0.3, 1.0),
                volatility_multiplier=0.7,
                shock_range=(-2.0, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-0.5, 0.5),
                volatility_multiplier=0.8,
                shock_range=(-1.5, -0.3),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(-0.5, 1.0),
                volatility_multiplier=0.8,
                shock_range=(-3.5, -1.0),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(2.0, 10.0),
                volatility_multiplier=1.3,
                shock_range=(-20.0, -7.0),
            ),
        },
        typical_event_types=["recovery_signal", "earnings_shock", "central_bank_decision"],
        correlation_tendency="low",
        benchmark_label="Growth (70% equities / 20% bonds / 10% gold)",
    ),

    RegimeType.TECH_BUBBLE: RegimeTemplate(
        type=RegimeType.TECH_BUBBLE,
        label="Tech Bubble",
        description=(
            "Speculative mania in tech and crypto. Extreme gains during the run-up, "
            "followed by severe correction risk. Bonds ignored. Gold sidelined."
        ),
        volatility_level=VolatilityLevel.HIGH,
        duration_turns_range=(12, 36),
        shock_probability_per_turn=0.15,
        asset_behaviors={
            AssetClass.EQUITIES: AssetBehavior(
                drift_range=(1.0, 6.0),
                volatility_multiplier=1.4,
                shock_range=(-15.0, -5.0),
            ),
            AssetClass.BONDS: AssetBehavior(
                drift_range=(-0.5, 0.3),
                volatility_multiplier=0.6,
                shock_range=(-2.0, -0.5),
            ),
            AssetClass.FX: AssetBehavior(
                drift_range=(-0.5, 0.5),
                volatility_multiplier=0.7,
                shock_range=(-1.5, -0.3),
            ),
            AssetClass.GOLD: AssetBehavior(
                drift_range=(-1.0, 0.5),
                volatility_multiplier=0.7,
                shock_range=(-3.0, -1.0),
            ),
            AssetClass.CRYPTO: AssetBehavior(
                drift_range=(3.0, 15.0),
                volatility_multiplier=1.5,
                shock_range=(-35.0, -12.0),
            ),
        },
        typical_event_types=[
            "earnings_shock", "regulatory_action", "crypto_selloff", "recovery_signal"
        ],
        correlation_tendency="mixed",
        benchmark_label="Speculative (50% equities / 10% bonds / 40% crypto)",
    ),
}


# ---------------------------------------------------------------------------
# Benchmark weights per regime
# ---------------------------------------------------------------------------
# Fixed-weight portfolio used as the comparison benchmark for each regime.
# Only asset_classes that are active in the scenario are used; the weights are
# then re-normalised by scenario_service.py so they always sum to exactly 1.0.
REGIME_BENCHMARK_WEIGHTS: Dict[str, Dict[str, float]] = {
    RegimeType.BULL_GROWTH:         {"equities": 0.60, "bonds": 0.30, "gold": 0.05, "crypto": 0.05},
    RegimeType.RECESSION:           {"equities": 0.20, "bonds": 0.60, "gold": 0.20},
    RegimeType.INFLATION_SHOCK:     {"equities": 0.30, "bonds": 0.20, "gold": 0.30, "fx": 0.20},
    RegimeType.RATE_HIKE_CYCLE:     {"equities": 0.30, "bonds": 0.50, "fx": 0.20},
    RegimeType.STAGFLATION:         {"equities": 0.25, "bonds": 0.25, "gold": 0.30, "fx": 0.20},
    RegimeType.BANKING_PANIC:       {"equities": 0.10, "bonds": 0.40, "gold": 0.30, "fx": 0.20},
    RegimeType.COMMODITY_BOOM:      {"equities": 0.35, "bonds": 0.20, "gold": 0.30, "fx": 0.15},
    RegimeType.GEOPOLITICAL_CRISIS: {"equities": 0.20, "bonds": 0.35, "gold": 0.35, "fx": 0.10},
    RegimeType.POST_CRASH_RECOVERY: {"equities": 0.70, "bonds": 0.20, "gold": 0.10},
    RegimeType.TECH_BUBBLE:         {"equities": 0.50, "bonds": 0.10, "crypto": 0.40},
}


# Which regimes are appropriate per difficulty level.
# Beginner starts in benign environments; advanced faces the harshest regimes.
DIFFICULTY_REGIMES: Dict[str, List[str]] = {
    Difficulty.BEGINNER: [
        RegimeType.BULL_GROWTH,
        RegimeType.POST_CRASH_RECOVERY,
        RegimeType.COMMODITY_BOOM,
    ],
    Difficulty.INTERMEDIATE: [
        RegimeType.RATE_HIKE_CYCLE,
        RegimeType.INFLATION_SHOCK,
        RegimeType.RECESSION,
        RegimeType.TECH_BUBBLE,
    ],
    Difficulty.ADVANCED: [
        RegimeType.STAGFLATION,
        RegimeType.BANKING_PANIC,
        RegimeType.GEOPOLITICAL_CRISIS,
    ],
}
