"""
Build the enriched historical-events dataset from normalised sources.

Reads each ``datasets/normalized/*.json`` file, applies the corresponding
rule function from ``rules.py``, and writes the combined output to
``datasets/curated/historical_events_enriched.json``.

Usage:
    python -m news_agent.enrichment.build_historical_events
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from .rules import (
    bls_inflation_events,
    ecb_policy_events,
    eia_oil_spike_events,
    fed_policy_events,
    nber_recession_events,
    nyfed_crisis_events,
)

# ── paths ─────────────────────────────────────────────────────────────────

_BASE = Path(__file__).resolve().parent.parent           # news_agent/
_NORM_DIR = _BASE / "datasets" / "normalized"
_CURATED_DIR = _BASE / "datasets" / "curated"
_OUTPUT_FILE = _CURATED_DIR / "historical_events_enriched.json"


def _load_normalized(filename: str) -> List[dict]:
    """Load records from a normalised JSON file."""
    path = _NORM_DIR / filename
    if not path.exists():
        print(f"  [SKIP] {filename} not found")
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("records", [])


# ── pipeline ──────────────────────────────────────────────────────────────

_SOURCES = [
    ("nber_business_cycles.json", nber_recession_events, "NBER recessions"),
    ("eia_oil_prices.json", eia_oil_spike_events, "EIA oil spikes"),
    ("bls_cpi_archive.json", bls_inflation_events, "BLS CPI inflation"),
    ("fed_monetary_policy.json", fed_policy_events, "Fed FOMC statements"),
    ("nyfed_crisis_timeline.json", nyfed_crisis_events, "NYFed crisis milestones"),
    ("ecb_mid_decisions.json", ecb_policy_events, "ECB policy items"),
]


def build() -> List[Dict[str, Any]]:
    """Run all enrichment rules and return the combined event list."""
    all_events: List[Dict[str, Any]] = []

    for filename, rule_fn, label in _SOURCES:
        records = _load_normalized(filename)
        if not records:
            print(f"  [{label}] 0 records loaded — skipped")
            continue

        derived = rule_fn(records)
        all_events.extend(derived)
        print(f"  [{label}] {len(records)} normalised → {len(derived)} enriched events")

    # Sort deterministically by event_id
    all_events.sort(key=lambda e: e["event_id"])
    return all_events


def write(events: List[Dict[str, Any]]) -> Path:
    """Write the enriched dataset to curated/."""
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "record_count": len(events),
        "note": (
            "Auto-generated by news_agent.enrichment.build_historical_events. "
            "Each record carries confidence and derivation_method fields."
        ),
        "events": events,
    }
    _OUTPUT_FILE.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return _OUTPUT_FILE


def main() -> None:
    print("=== news_agent enrichment pipeline ===\n")
    events = build()
    out = write(events)
    print(f"\nTotal: {len(events)} enriched events → {out}")

    # Quick category breakdown
    cats: Dict[str, int] = {}
    for e in events:
        cat = e["category"]
        cats[cat] = cats.get(cat, 0) + 1
    print("\nCategory breakdown:")
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")


if __name__ == "__main__":
    main()
